### ISSUE TITLE
Error message when scraping the Boston Globe

### ISSUE THREAD

**Issue by mmespeer** [jpd236/CrosswordScraper#13] opened 2022-03-06 14:50 UTC
I received an error messahe while trying to scrape the Boston Globe puzzle on March 6
https://www.bostonglobe.com/games-comics/crossword/?p1=BGMenu_Sections

**Comment by jpd236** [comment] 2022-03-06 17:47
Thanks, reproduced on my end as well. Not sure why this broke, but taking a look.

**Comment by jpd236** [comment] 2022-03-06 21:22
This should be fixed in version 1.2.8.

I'll upload this release to the Firefox and Chrome stores shortly; typically, Firefox approves new versions within a few minutes, and Chrome within one day, though in some situations it can take longer. If you want to be able to scrape this puzzle before the end of the day - since as far as I know, the Boston Globe doesn't have an archive available - you can either use Firefox in a few minutes once this version is (hopefully) available, or else manually install the release using the instructions at https://github.com/jpd236/CrosswordScraper/wiki/Troubleshooting#installing-a-custom-release-in-chrome. If you follow the latter steps, just be sure to revert back to the standard version at some point to avoid missing out on future updates.

**Closed by jpd236** 2022-03-06 21:22 UTC

**Comment by mmespeer** [comment] 2022-03-07 00:21
Thanks


Sent from Yahoo Mail for iPhone


On Sunday, March 6, 2022, 4:22 PM, Jeff Davidson ***@***.***> wrote:




This should be fixed in version 1.2.8.

I'll upload this release to the Firefox and Chrome stores shortly; typically, Firefox approves new versions within a few minutes, and Chrome within one day, though in some situations it can take longer. If you want to be able to scrape this puzzle before the end of the day - since as far as I know, the Boston Globe doesn't have an archive available - you can either use Firefox in a few minutes once this version is (hopefully) available, or else manually install the release using the instructions at https://github.com/jpd236/CrosswordScraper/wiki/Troubleshooting#installing-a-custom-release-in-chrome. If you follow the latter steps, just be sure to revert back to the standard version at some point to avoid missing out on future updates.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
